"""
Position lifecycle types: Position, Order, Trade, ExitReason.
See SPEC.md §12 (Equity Tracking) and §13-16 (per-strategy state machines).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class ExitReason(str, Enum):
    STOP = "stop"
    TRAILING = "trailing"
    SIGNAL = "signal"               # close-based rule (e.g., close < EMA50)
    CHANNEL = "channel"             # Donchian channel exit (D)
    CIRCUIT_BREAKER = "circuit"     # A: daily/weekly/DD circuit halt
    DRAWDOWN_HALT = "dd_halt"       # C: permanent drawdown halt
    LIQUIDATION = "liquidation"     # Futures 2x liquidation
    REGIME_FLIP = "regime_flip"     # A: opposing daily regime
    END_OF_BACKTEST = "eob"


class OrderAction(str, Enum):
    OPEN_LONG = "open_long"
    OPEN_SHORT = "open_short"
    CLOSE = "close"


@dataclass
class Order:
    """Order generated by a strategy at bar close, executed at next bar open."""
    action: OrderAction
    notional: float = 0.0           # for OPEN: target notional (USD)
    initial_stop: float = 0.0       # for OPEN with stop-loss (A, B, C)
    reason: str = ""                # human-readable, for trade log
    atr_at_signal: float = 0.0      # captured for stop/trailing reference


@dataclass
class Position:
    """Open position. Tracked by engine while in market."""
    trade_id: int
    side: str                        # 'long' or 'short'
    units: float                     # number of BTC units
    entry_price: float               # actual fill price (with slippage)
    entry_time: datetime
    mode: str                        # 'spot_1x', 'futures_1x', 'futures_2x'
    notional_at_entry: float         # entry_price * units

    # Stop tracking (used by A, B, C — not D)
    current_stop: Optional[float] = None
    state: str = "INITIAL"           # state machine: 'INITIAL', 'BREAKEVEN_TRAIL', 'TRAILING'
    peak_high: Optional[float] = None        # for long trailing (A, C use high)
    trough_low: Optional[float] = None       # for short trailing
    peak_close: Optional[float] = None       # for B's highest-close trailing
    atr_at_entry: Optional[float] = None     # captured at entry for break-even

    # Liquidation price (futures 2x only; None for spot/1x)
    liquidation_price: Optional[float] = None

    @property
    def side_sign(self) -> int:
        return 1 if self.side == "long" else -1

    @property
    def is_long(self) -> bool:
        return self.side == "long"

    @property
    def is_short(self) -> bool:
        return self.side == "short"

    @property
    def is_spot(self) -> bool:
        return self.mode == "spot_1x"

    @property
    def is_futures(self) -> bool:
        return self.mode.startswith("futures_")

    def unrealized_pnl(self, current_price: float) -> float:
        """USD unrealized PnL at given price."""
        return (current_price - self.entry_price) * self.units * self.side_sign


@dataclass
class Trade:
    """Closed roundtrip — for trade log and metrics."""
    trade_id: int
    side: str
    entry_time: datetime
    entry_price: float               # actual fill (with slippage)
    exit_time: datetime
    exit_price: float                # actual fill (with slippage)
    units: float
    notional_at_entry: float
    mode: str
    pnl_usd: float                   # net PnL after all costs
    pnl_pct: float                   # as fraction of equity at entry
    fees_paid_usd: float
    funding_paid_usd: float          # cumulative; positive = paid, negative = received
    slippage_cost_usd: float
    exit_reason: ExitReason
    equity_at_entry: float
    equity_at_exit: float
    hold_bars: int                   # number of bars held
    hold_days: float                 # calendar days

    @property
    def is_winner(self) -> bool:
        return self.pnl_usd > 0
